apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      # --- Cấu hình chạy trên Spot VM để tối ưu chi phí ---
      nodeSelector:
        cloud.google.com/gke-spot: "true"
      tolerations:
      - key: "cloud.google.com/gke-spot"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
      
      containers:
      - name: frontend
        image: IMAGE_PLACEHOLDER_FRONTEND
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: LoadBalancer # Cấp phát IP Public để truy cập giao diện từ ngoài Internet
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: frontend
